name: Nightly Build

on:
  schedule:
    - cron: '0 0 * * *' # Minutes Hours DayOfMonth Month DayOfWeek

  workflow_dispatch:

jobs:
  assemble:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.0
        with:
          java-version: 17
          distribution: "temurin"
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Bump version
        uses: chkfung/android-version-actions@v1.2.0
        with:
            gradle-path: app/build.gradle.kts # Path to the build.gradle file
            version-code: ${{ github.run_number }}
            version-name: $( ./gradlew -q app:printVersionName )

      - name: Assemble APK
        run: ./gradlew assemble

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Release APK
          path: app/build/outputs/apk/release/app-release.apk
