name: Nightly Build

on:
  schedule:
    - cron: '0 0 * * *' # Minutes Hours DayOfMonth Month DayOfWeek

  workflow_dispatch:

jobs:
  assemble:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.0
        with:
          java-version: 17
          distribution: "temurin"
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Bump version
        uses: chkfung/android-version-actions@v1.2.2
        with:
            gradlePath: app/build.gradle.kts # Path to the build.gradle file
            versionCode: ${{ github.run_number }}
            versionName: $( ./gradlew -q app:printVersionName )

      - name: Assemble APK
        run: ./gradlew assemble

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Release APK
          path: app/build/outputs/apk/release/app-release-unsigned.apk

  distribute:
    runs-on: ubuntu-latest

    needs: ["assemble"]

    steps:
      - uses: actions/checkout@v4

      - name: Download APK
        uses: actions/download-artifact@master
        with:
          name: Release APK
          path: ./

      - name: Upload Artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: ./app-release.apk