name: Release & Deploy

on:
  push:
    branches:
      - "release/*"
jobs:
  assemble:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.0
        with:
          java-version: 17
          distribution: "temurin"
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Bump version
        uses: chkfung/android-version-actions@v1.2.2
        with:
          gradlePath: app/build.gradle.kts # Path to the build.gradle file
          versionCode: ${{ github.run_number }}

      - name: Store api.properties Encoded
        run: echo ${{ secrets.API_PROPERTIES }} > api.properties.encoded

      - name: Create api.properties
        run: base64 --decode api.properties.encoded > api.properties

      - name: Create Google Services JSON
        run: echo ${{ secrets.GOOGLE_SERVICES_JSON }} > google-services.json

      - name: Assemble APK
        run: ./gradlew assemble

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Release APK
          path: app/build/outputs/apk/release/app-release-unsigned.apk